#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["App/Learning.Docker.Api/Learning.Docker.Api.csproj", "App/Learning.Docker.Api/"]
COPY ["Common/Learning.Common.Api/Learning.Common.Api.csproj", "Common/Learning.Common.Api/"]
COPY ["Common/Learning.Common/Learning.Common.csproj", "Common/Learning.Common/"]
RUN dotnet restore "./App/Learning.Docker.Api/Learning.Docker.Api.csproj"
COPY . .
WORKDIR "/src/App/Learning.Docker.Api"
RUN dotnet build "./Learning.Docker.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Learning.Docker.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Learning.Docker.Api.dll"]