# Build Stage

FROM mydotnetsdk:8.0 AS build-env
WORKDIR /source
COPY . .
# List files in the current directory
## RUN ls -la

# List files in the /source directory
## RUN ls -la /source

RUN dotnet restore "DockerAppsDemo.csproj" --disable-parallel
RUN dotnet publish "DockerAppsDemo.csproj" -c release -o /app --no-restore

# Serve Stage
FROM mydotnetruntime:8.0
WORKDIR /amittestdemo
COPY --from=build-env /app .

EXPOSE 8080
EXPOSE 7223
EXPOSE 7224

ENTRYPOINT ["dotnet", "DockerAppsDemo.dll"]